## .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: c

sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh install_bioc_deps

script:
   - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - BOOTSTRAP_LATEX=true # Required to build pdf vignettes (+ manual); slower
    - R_CHECK_ARGS="--no-vignettes --timings" # Mimic BioC build machines
  matrix:
    - RVERSION=3.2.2 # BioC 3.2 uses R 3.2.x. Needs to be manually updated upon new BioC version
